set nocompatible

execute pathogen#infect()


" Basic options
filetype indent plugin on
syntax on
set number
set backspace=indent,eol,start
set history=500
set showcmd
set showmode
set autoread
set encoding=utf-8
set laststatus=2
set visualbell
set mouse=a
"set cmdheight=2
"set wildmenu
set hidden

" Colours
"set t_Co=256
let base16colorspace=256
colorscheme base16-eighties
set background=dark

" Turn off swap files
set noswapfile
set nobackup
set nowb

" Indentation
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab

" Search
set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

set scrolloff=5
set ruler
set showmatch

" Auto-reload vimrc
augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

map <C-n> :NERDTreeToggle<CR>
