#!/bin/bash


if [ $# -eq 0 ]; then
    # if no arguments are passed, launch fzf to select a scheme
    scheme=$(find ~/dotfiles/base16/schemes -type f -exec basename \{} .yaml \; | sort | fzf)
    if [[ $scheme = "" ]]; then
        exit 0
    fi
else
    # if an argument is passed, install that scheme
    scheme=$1
fi

python3 ~/dotfiles/base16/base16-selector.py $scheme bash neovim i3 sway swaynag
